(function(){
 const NAV=[
  ['Inicio',[['centro-operaciones','Centro de Operaciones','layout-dashboard'],['','Panel de Talento','home']]],
  ['Autogestión',[['mi-portal','Mi portal','user']]],
  ['Administración',[['personas','Personas','users'],['expediente-laboral','Expediente laboral','folder'],['organizacion','Organización','workflow'],['sigep','SIGEP y cumplimiento','badge-check'],['documentos','Documentos y firma','file'],['generador-documentos','Generador de actos','file-text'],['activos','Activos asignados','monitor']]],
  ['Empleo público',[['empleo-publico','Planta y empleo público','briefcase'],['planeacion-th','Planeación estratégica TH','chart'],['situaciones-administrativas','Situaciones administrativas','calendar'],['integridad-publica','Integridad y declaraciones','shield'],['retiro','Retiro y transferencia','route']]],
  ['Ciclo de vida',[['seleccion','Selección','search'],['onboarding','Incorporación','route']]],
  ['Tiempo y pagos',[['asistencia','Asistencia','calendar'],['ausencias','Ausencias y vacaciones','calendar'],['nomina','Nómina pública','wallet'],['vencimientos','Vencimientos y obligaciones','alarm-clock']]],
  ['Desarrollo',[['desempeno','Desempeño público','chart'],['capacitacion','Capacitación','graduation-cap']]],
  ['Cultura y seguridad',[['bienestar-sst','Bienestar y SG-SST','heart'],['comunicaciones','Comunicaciones','message'],['canal-etico','Canal ético','shield']]],
  ['Operación y control',[['flujos','Flujos y aprobaciones','workflow'],['integraciones-oficiales','Integraciones oficiales','plug'],['permisos','Roles y permisos','key'],['auditoria','Auditoría del sistema','history']]],
  ['Analítica',[['analitica','People Analytics','chart']]]
 ];
 const HR={data:null,async init(config){this.config=config||{};this.data=await ERP.fetchJSON('data.json',{});this.renderNav();this.renderMetrics();this.bindGeneric();if(this.config.init)this.config.init(this.data,this);ERP.refreshIcons()},
  renderNav(){const nav=document.querySelector('.hr-sidebar-nav');if(!nav)return;const path=location.pathname.replace(/\\/g,'/'),root=/\/talento-humano\/?(?:index\.html)?$/.test(path),prefix=root?'':'../';let html='';for(const [group,links] of NAV){html+=`<details class="hr-nav-section" open><summary>${group}</summary>`+links.map(([slug,label,icon])=>{const href=slug?`${prefix}${slug}/index.html`:`${prefix}index.html`,active=slug?(path.includes(`/talento-humano/${slug}/`)):(root);return `<a class="nav-item${active?' active':''}" href="${href}"><i data-lucide="${icon}"></i><span class="nav-text">${label}</span></a>`}).join('')+'</details>'}html+=`<div class="nav-label">Secretaría General</div><a class="nav-item" href="${root?'../':'../../'}index.html"><i data-lucide="arrow-left"></i><span class="nav-text">Volver al panel general</span></a><a class="nav-item" href="${root?'../../../':'../../../../'}index.html"><i data-lucide="grid"></i><span class="nav-text">Todas las dependencias</span></a>`;nav.innerHTML=html},
  renderMetrics(){const el=document.getElementById('metrics');if(!el||!this.data.metrics)return;el.innerHTML=this.data.metrics.map(m=>`<article class="card metric-card hr-kpi ${m.tone||''}"><div class="metric-copy"><span>${m.label}</span><strong>${m.value}</strong><small>${m.hint||''}</small>${m.delta?`<div class="metric-delta ${m.deltaTone||'up'}">${m.delta}</div>`:''}</div><div class="metric-icon"><i data-lucide="${m.icon||'chart'}"></i></div></article>`).join('')},
  bindGeneric(){document.addEventListener('click',e=>{const modal=e.target.closest('[data-modal-open]');if(modal)ERP.open(modal.dataset.modalOpen);const demo=e.target.closest('[data-demo-action]');if(demo)ERP.toast(demo.dataset.demoAction);const exp=e.target.closest('[data-export]');if(exp){const key=exp.dataset.export;ERP.csv(`${key}.csv`,this.data[key]||[])}})},
  status(value){const v=String(value||'').toLowerCase();if(/activo|aprob|complet|vigente|presente|firmado|pagado|cerrado|cumplido|finalizado|bajo|sincronizado/.test(v))return'status-success';if(/pendiente|proceso|próximo|proximo|revisión|revision|parcial|medio|tarde|devuelto/.test(v))return'status-warning';if(/rechaz|venc|alto|ausente|incumpl|crítico|critico|retirado|fallido|bloqueado/.test(v))return'status-danger';if(/programado|radicado|nuevo|publicado|abierto|entrevista|oferta|enviado/.test(v))return'status-info';return'status-neutral'},
  initials:ERP.initials,money(v){return new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(v||0))},number(v){return new Intl.NumberFormat('es-CO').format(Number(v||0))},save(k,v){localStorage.setItem(`erp-th-${k}`,JSON.stringify(v))},load(k,f=[]){try{return JSON.parse(localStorage.getItem(`erp-th-${k}`)||'null')??f}catch{return f}},merge(k,b=[]){return[...this.load(k,[]),...b]},openDrawer(t,s,h){const d=document.getElementById('hrDrawer'),b=document.getElementById('hrDrawerBackdrop');if(!d||!b)return;document.getElementById('hrDrawerTitle').textContent=t;document.getElementById('hrDrawerSubtitle').textContent=s||'';document.getElementById('hrDrawerContent').innerHTML=h;b.classList.remove('hidden');d.classList.remove('hidden');document.body.style.overflow='hidden';ERP.refreshIcons()},closeDrawer(){document.getElementById('hrDrawer')?.classList.add('hidden');document.getElementById('hrDrawerBackdrop')?.classList.add('hidden');document.body.style.overflow=''},bindForm(id,key,transform,onSaved){const f=document.getElementById(id);if(!f)return;f.addEventListener('submit',e=>{e.preventDefault();const o=transform(new FormData(f),this),saved=this.load(key,[]);saved.unshift(o);this.save(key,saved);ERP.close(f.closest('.modal-backdrop').id);f.reset();ERP.toast('Registro guardado en modo demostración');if(onSaved)onSaved(o)})},filterRows(rows,q,fields){q=String(q||'').toLowerCase().trim();return!q?rows:rows.filter(r=>fields.some(f=>String(r[f]||'').toLowerCase().includes(q)))},uid(p){return ERP.uid(p)},date:ERP.formatDate};window.HR=HR;window.closeHRDrawer=()=>HR.closeDrawer();})();