(function(){
 const O={data:null,active:null,rows:{},moduleId:'ops',
  async init(config={}){this.config=config;this.data=await ERP.fetchJSON('data.json',{});this.moduleId=this.data.moduleId||location.pathname.split('/').filter(Boolean).slice(-2,-1)[0]||'ops';this.active=this.data.sections?.[0]?.id;this.load();this.metrics();this.nav();this.panels();this.bind();if(config.after)this.config.after(this.data,this);ERP.refreshIcons()},
  load(){for(const s of this.data.sections||[]){this.rows[s.id]=[...HR.load(`${this.moduleId}-${s.id}`,[]),...(s.rows||[])]}},
  metrics(){const el=document.getElementById('opsMetrics');if(!el)return;el.innerHTML=(this.data.metrics||[]).map(m=>`<article class="card metric-card"><div class="metric-copy"><span>${m.label}</span><strong>${m.value}</strong><small>${m.hint||''}</small></div><div class="metric-icon"><i data-lucide="${m.icon||'chart'}"></i></div></article>`).join('')},
  nav(){const el=document.getElementById('opsSections');if(!el)return;el.innerHTML=(this.data.sections||[]).map((s,i)=>`<button class="ops-section-btn ${i===0?'active':''}" data-ops-section="${s.id}"><i data-lucide="${s.icon||'file'}"></i><span>${s.label}</span><b>${this.rows[s.id].length}</b></button>`).join('')},
  panels(){const el=document.getElementById('opsPanels');if(!el)return;el.innerHTML=(this.data.sections||[]).map((s,i)=>`<section class="ops-panel ${i===0?'active':''}" data-ops-panel="${s.id}"><div class="ops-panel-title"><div><h2>${s.label}</h2><p>${s.description||''}</p></div>${s.action?`<button class="btn btn-secondary btn-sm" data-section-action="${s.id}">${s.action}</button>`:''}</div><div data-ops-render="${s.id}"></div></section>`).join('');for(const s of this.data.sections||[])this.render(s)},
  visible(s){let rows=[...this.rows[s.id]];const q=(document.getElementById('opsSearch')?.value||'').toLowerCase().trim();const st=document.getElementById('opsStatus')?.value||'';if(q)rows=rows.filter(r=>Object.values(r).some(v=>String(v??'').toLowerCase().includes(q)));if(st)rows=rows.filter(r=>String(r.status||r.estado||'')===st);return rows},
  render(s){const el=document.querySelector(`[data-ops-render="${s.id}"]`);if(!el)return;const rows=this.visible(s);el.innerHTML=s.layout==='cards'?this.cards(s,rows):s.layout==='timeline'?this.timeline(s,rows):this.table(s,rows);ERP.refreshIcons()},
  table(s,rows){const cols=s.columns||[];return `<div class="ops-table-wrap"><table class="ops-table"><thead><tr>${cols.map(c=>`<th>${c.label}</th>`).join('')}<th>Acciones</th></tr></thead><tbody>${rows.length?rows.map((r,i)=>`<tr>${cols.map(c=>`<td>${this.cell(c,r[c.key],r)}</td>`).join('')}<td><div class="ops-row-actions"><button class="icon-btn" data-ops-detail="${s.id}|${i}" title="Ver"><i data-lucide="eye"></i></button><button class="icon-btn" data-ops-cycle="${s.id}|${i}" title="Avanzar"><i data-lucide="check"></i></button></div></td></tr>`).join(''):`<tr><td colspan="${cols.length+1}"><div class="ops-empty">No hay registros para los filtros aplicados.</div></td></tr>`}</tbody></table></div>`},
  cell(c,v,r){if(c.type==='status')return `<span class="status ${HR.status(v)}">${v||'Sin estado'}</span>`;if(c.type==='date')return HR.date(v);if(c.type==='money')return HR.money(v);if(c.type==='progress')return `<div style="min-width:100px"><div class="ops-progress"><span style="width:${Number(v)||0}%"></span></div><small>${Number(v)||0}%</small></div>`;if(c.type==='priority')return `<span class="ops-priority ${String(v||'normal').toLowerCase()}">${v||'Normal'}</span>`;if(c.type==='primary')return `<strong>${v??''}</strong>${r.subtitle?`<small>${r.subtitle}</small>`:''}`;return String(v??'—')},
  cards(s,rows){return `<div class="ops-card-grid">${rows.map((r,i)=>`<article class="ops-record ops-card"><div class="ops-record-top"><div class="ops-icon"><i data-lucide="${r.icon||s.icon||'file'}"></i></div><span class="status ${HR.status(r.status||r.estado)}">${r.status||r.estado||'Activo'}</span></div><h3>${r.title||r.name||r.nombre||r.code||'Registro'}</h3><p>${r.description||r.detail||r.descripcion||''}</p><div class="ops-record-meta">${Object.entries(r).filter(([k])=>!['title','name','nombre','description','detail','descripcion','icon','status','estado','subtitle','id'].includes(k)).slice(0,4).map(([k,v])=>`<div><span>${this.pretty(k)}</span><strong>${v}</strong></div>`).join('')}</div><footer><small>${r.subtitle||''}</small><button class="btn btn-secondary btn-sm" data-ops-detail="${s.id}|${i}">Ver detalle</button></footer></article>`).join('')}</div>`},
  timeline(s,rows){return `<div class="ops-timeline">${rows.map((r,i)=>`<article class="ops-timeline-item"><strong>${r.title||r.name||r.nombre}</strong><p>${r.description||r.detail||''}</p><footer><span>${r.date||r.fecha||''}</span><span class="status ${HR.status(r.status||r.estado)}">${r.status||r.estado||''}</span><button class="btn btn-secondary btn-sm" data-ops-detail="${s.id}|${i}">Abrir</button></footer></article>`).join('')}</div>`},
  pretty(k){return k.replace(/([A-Z])/g,' $1').replace(/_/g,' ').replace(/^./,x=>x.toUpperCase())},
  bind(){document.addEventListener('click',e=>{const s=e.target.closest('[data-ops-section]');if(s){this.active=s.dataset.opsSection;document.querySelectorAll('[data-ops-section]').forEach(x=>x.classList.toggle('active',x===s));document.querySelectorAll('[data-ops-panel]').forEach(x=>x.classList.toggle('active',x.dataset.opsPanel===this.active));this.render(this.data.sections.find(x=>x.id===this.active))}const d=e.target.closest('[data-ops-detail]');if(d)this.detail(d.dataset.opsDetail);const c=e.target.closest('[data-ops-cycle]');if(c)this.cycle(c.dataset.opsCycle);if(e.target.closest('#opsExport'))this.export();if(e.target.closest('#opsNew'))this.openForm()});document.getElementById('opsSearch')?.addEventListener('input',()=>this.render(this.data.sections.find(x=>x.id===this.active)));document.getElementById('opsStatus')?.addEventListener('change',()=>this.render(this.data.sections.find(x=>x.id===this.active)));document.getElementById('opsForm')?.addEventListener('submit',e=>this.save(e))},
  detail(key){const [sid,idx]=key.split('|'),s=this.data.sections.find(x=>x.id===sid),r=this.visible(s)[Number(idx)];if(!r)return;HR.openDrawer('Detalle',s.label,`<div class="hr-detail-hero"><div class="avatar">${ERP.initials(r.title||r.name||r.nombre||r.code||'TH')}</div><div><h2>${r.title||r.name||r.nombre||r.code||'Registro'}</h2><p>${r.description||r.detail||r.descripcion||''}</p></div></div><div class="ops-detail-grid">${Object.entries(r).map(([k,v])=>`<div class="ops-detail"><span>${this.pretty(k)}</span><strong>${Array.isArray(v)?v.join(', '):v}</strong></div>`).join('')}</div>`)},
  cycle(key){const [sid,idx]=key.split('|'),s=this.data.sections.find(x=>x.id===sid),r=this.visible(s)[Number(idx)];if(!r)return;const f='status' in r?'status':'estado',states=this.data.statusCycle||['Pendiente','En proceso','Completado'];const p=states.indexOf(r[f]);r[f]=states[(p+1)%states.length];this.render(s);ERP.toast(`Estado actualizado a ${r[f]}`)},
  openForm(){const f=this.data.form;if(!f){ERP.toast('El formulario se habilitará al conectar la base de datos');return}document.getElementById('opsFormTitle').textContent=f.title||'Nuevo registro';document.getElementById('opsFormFields').innerHTML=(f.fields||[]).map(x=>`<div class="ops-form-group ${x.full?'full':''}"><label>${x.label}</label>${x.type==='select'?`<select name="${x.key}" ${x.required?'required':''}>${(x.options||[]).map(o=>`<option>${o}</option>`).join('')}</select>`:x.type==='textarea'?`<textarea name="${x.key}" ${x.required?'required':''}></textarea>`:`<input name="${x.key}" type="${x.type||'text'}" ${x.required?'required':''}>`}</div>`).join('');ERP.open('opsFormModal')},
  save(e){e.preventDefault();const f=this.data.form,obj=Object.fromEntries(new FormData(e.currentTarget).entries());obj.id=HR.uid('TH');const saved=HR.load(`${this.moduleId}-${f.sectionId}`,[]);saved.unshift(obj);HR.save(`${this.moduleId}-${f.sectionId}`,saved);this.rows[f.sectionId].unshift(obj);ERP.close('opsFormModal');e.currentTarget.reset();this.nav();this.render(this.data.sections.find(x=>x.id===f.sectionId));ERP.toast('Registro guardado en modo demostración')},
  export(){const s=this.data.sections.find(x=>x.id===this.active);ERP.csv(`${this.moduleId}-${s.id}.csv`,this.visible(s))}
 };window.HROps=O;
})();