
(function(){
 const P={data:null,config:null,active:null,rows:{},
  async init(config={}){this.config=config;this.data=await ERP.fetchJSON('data.json',{});this.active=this.data.sections?.[0]?.id;this.loadRows();this.renderMetrics();this.renderNavigation();this.renderInsights();this.renderPanels();this.bind();ERP.refreshIcons()},
  loadRows(){for(const s of this.data.sections||[]){const local=HR.load(`${this.data.moduleId}-${s.id}`,[]);this.rows[s.id]=[...local,...(s.rows||[])]}},
  renderMetrics(){const el=document.getElementById('metrics');if(!el)return;el.innerHTML=(this.data.metrics||[]).map(m=>`<article class="card metric-card public-kpi"><div class="metric-copy"><span>${m.label}</span><strong>${m.value}</strong><small>${m.hint||''}</small></div><div class="metric-icon"><i data-lucide="${m.icon||'chart'}"></i></div></article>`).join('')},
  renderNavigation(){const el=document.getElementById('publicSections');if(!el)return;el.innerHTML=(this.data.sections||[]).map((s,i)=>`<button class="public-section-btn ${i===0?'active':''}" data-section="${s.id}"><i data-lucide="${s.icon||'file'}"></i><span>${s.label}</span><b>${this.rows[s.id].length}</b></button>`).join('')},
  renderInsights(){const el=document.getElementById('publicInsights');if(!el)return;el.innerHTML=(this.data.insights||[]).map(x=>`<article class="card public-insight"><span>${x.label}</span><strong>${x.value}</strong><p>${x.detail}</p></article>`).join('')},
  renderPanels(){const el=document.getElementById('publicPanels');if(!el)return;el.innerHTML=(this.data.sections||[]).map((s,i)=>`<section class="public-panel ${i===0?'active':''}" data-panel="${s.id}"><div class="public-panel-head"><div><h2>${s.label}</h2><p>${s.description||''}</p></div></div><div data-render="${s.id}"></div></section>`).join('');for(const s of this.data.sections||[])this.renderSection(s)},
  visibleRows(s){let rows=[...this.rows[s.id]];const q=(document.getElementById('publicSearch')?.value||'').toLowerCase().trim();const st=document.getElementById('publicStatus')?.value||'';if(q)rows=rows.filter(r=>Object.values(r).some(v=>String(v??'').toLowerCase().includes(q)));if(st)rows=rows.filter(r=>String(r.status||r.estado||'')===st);return rows},
  renderSection(s){const el=document.querySelector(`[data-render="${s.id}"]`);if(!el)return;const rows=this.visibleRows(s);if(s.layout==='cards')el.innerHTML=this.cards(s,rows);else if(s.layout==='checklist')el.innerHTML=this.checklist(s,rows);else if(s.layout==='timeline')el.innerHTML=this.timeline(s,rows);else if(s.layout==='matrix')el.innerHTML=this.matrix(s,rows);else el.innerHTML=this.table(s,rows);ERP.refreshIcons()},
  table(s,rows){const cols=s.columns||[];return `<div class="public-table-wrap"><table class="public-table"><thead><tr>${cols.map(c=>`<th>${c.label}</th>`).join('')}<th>Acciones</th></tr></thead><tbody>${rows.length?rows.map((r,idx)=>`<tr>${cols.map((c,i)=>`<td>${this.cell(c,r[c.key],r,i)}</td>`).join('')}<td><div class="row-actions"><button class="icon-btn" data-detail="${s.id}|${idx}" title="Ver detalle"><i data-lucide="file"></i></button><button class="icon-btn" data-cycle="${s.id}|${idx}" title="Avanzar estado"><i data-lucide="check"></i></button></div></td></tr>`).join(''):`<tr><td colspan="${cols.length+1}"><div class="empty-state"><h3>Sin registros</h3><p>No hay resultados para los filtros aplicados.</p></div></td></tr>`}</tbody></table></div>`},
  cell(c,v,r,i){if(c.type==='status')return `<span class="status ${HR.status(v)}">${v||'Sin estado'}</span>`;if(c.type==='progress')return `<div style="min-width:110px"><div class="public-progress"><span style="width:${Number(v)||0}%"></span></div><small>${Number(v)||0}%</small></div>`;if(c.type==='money')return HR.money(v);if(c.type==='date')return HR.date(v);if(c.type==='primary'||i===0)return `<strong>${v??''}</strong>${r.subtitle?`<small>${r.subtitle}</small>`:''}`;return String(v??'—')},
  cards(s,rows){return `<div class="public-card-grid">${rows.map((r,idx)=>`<article class="card public-record-card"><div class="public-record-top"><div class="public-record-icon"><i data-lucide="${r.icon||s.icon||'file'}"></i></div><span class="status ${HR.status(r.status||r.estado)}">${r.status||r.estado||'Activo'}</span></div><h3>${r.title||r.name||r.nombre||r.code||'Registro'}</h3><p>${r.description||r.detail||r.descripcion||''}</p><div class="public-record-meta">${Object.entries(r).filter(([k])=>!['title','name','nombre','description','detail','descripcion','icon','status','estado','subtitle','id'].includes(k)).slice(0,4).map(([k,v])=>`<div><span>${this.pretty(k)}</span><strong>${v}</strong></div>`).join('')}</div><footer class="public-record-foot"><small>${r.subtitle||''}</small><button class="btn btn-secondary btn-sm" data-detail="${s.id}|${idx}">Ver detalle</button></footer></article>`).join('')}</div>`},
  checklist(s,rows){return `<div class="public-check-list">${rows.map((r,idx)=>`<article class="public-check-item"><div class="public-check-icon"><i data-lucide="${r.icon||'check'}"></i></div><div class="public-check-copy"><strong>${r.title||r.name||r.nombre}</strong><p>${r.description||r.detail||''}</p><small>${r.owner||r.responsable||''}${r.due?` · ${r.due}`:''}</small></div><div><span class="status ${HR.status(r.status||r.estado)}">${r.status||r.estado}</span><button class="icon-btn" data-detail="${s.id}|${idx}"><i data-lucide="file"></i></button></div></article>`).join('')}</div>`},
  timeline(s,rows){return `<div class="public-timeline">${rows.map((r,idx)=>`<div class="public-timeline-item"><article class="public-timeline-card" data-detail="${s.id}|${idx}"><strong>${r.title||r.name||r.nombre}</strong><p>${r.description||r.detail||''}</p><footer><span>${r.date||r.fecha||''}</span><span class="status ${HR.status(r.status||r.estado)}">${r.status||r.estado||''}</span></footer></article></div>`).join('')}</div>`},
  matrix(s,rows){return `<div class="public-matrix">${rows.map((r,idx)=>`<article class="public-matrix-card"><strong>${r.title||r.name||r.nombre}</strong><p>${r.description||r.detail||''}</p><div class="public-progress"><span style="width:${Number(r.progress||r.avance)||0}%"></span></div><footer><span>${r.owner||r.responsable||''}</span><button class="btn btn-secondary btn-sm" data-detail="${s.id}|${idx}">Abrir</button></footer></article>`).join('')}</div>`},
  pretty(k){return k.replace(/([A-Z])/g,' $1').replace(/_/g,' ').replace(/^./,x=>x.toUpperCase())},
  bind(){document.addEventListener('click',e=>{const sec=e.target.closest('[data-section]');if(sec){this.active=sec.dataset.section;document.querySelectorAll('[data-section]').forEach(x=>x.classList.toggle('active',x===sec));document.querySelectorAll('[data-panel]').forEach(x=>x.classList.toggle('active',x.dataset.panel===this.active));this.renderSection(this.data.sections.find(x=>x.id===this.active))}const det=e.target.closest('[data-detail]');if(det)this.detail(det.dataset.detail);const cyc=e.target.closest('[data-cycle]');if(cyc)this.cycle(cyc.dataset.cycle);const add=e.target.closest('#newPublicRecord');if(add)this.openForm();const exp=e.target.closest('#exportPublic');if(exp)this.exportActive()});document.getElementById('publicSearch')?.addEventListener('input',()=>this.renderSection(this.data.sections.find(x=>x.id===this.active)));document.getElementById('publicStatus')?.addEventListener('change',()=>this.renderSection(this.data.sections.find(x=>x.id===this.active)));document.getElementById('publicForm')?.addEventListener('submit',e=>this.save(e))},
  detail(key){const [sid,idx]=key.split('|');const r=this.visibleRows(this.data.sections.find(x=>x.id===sid))[Number(idx)];if(!r)return;const html=`<div class="hr-detail-hero"><div class="avatar">${ERP.initials(r.title||r.name||r.nombre||r.code||'TH')}</div><div><h2>${r.title||r.name||r.nombre||r.code||'Detalle'}</h2><p>${r.description||r.detail||r.descripcion||''}</p></div></div><div class="public-detail-grid">${Object.entries(r).filter(([k])=>!['description','detail','descripcion'].includes(k)).map(([k,v])=>`<div class="public-detail-item"><span>${this.pretty(k)}</span><strong>${v}</strong></div>`).join('')}</div>`;HR.openDrawer('Detalle del registro',this.data.title,html)},
  cycle(key){const [sid,idx]=key.split('|');const s=this.data.sections.find(x=>x.id===sid);const r=this.visibleRows(s)[Number(idx)];if(!r)return;const field=('status' in r)?'status':'estado';const states=this.data.statusCycle||['Pendiente','En proceso','Completado'];const p=states.indexOf(r[field]);r[field]=states[(p+1)%states.length];this.renderSection(s);ERP.toast(`Estado actualizado a ${r[field]}`)},
  openForm(){const f=this.data.form||{};document.getElementById('publicFormTitle').textContent=f.title||'Nuevo registro';document.getElementById('publicFormFields').innerHTML=(f.fields||[]).map(x=>`<div class="public-form-group ${x.full?'full':''}"><label>${x.label}</label>${x.type==='select'?`<select name="${x.key}" ${x.required?'required':''}>${(x.options||[]).map(o=>`<option>${o}</option>`).join('')}</select>`:x.type==='textarea'?`<textarea name="${x.key}" ${x.required?'required':''}></textarea>`:`<input name="${x.key}" type="${x.type||'text'}" ${x.required?'required':''}>`}</div>`).join('');ERP.open('publicFormModal')},
  save(e){e.preventDefault();const f=this.data.form||{};const obj=Object.fromEntries(new FormData(e.currentTarget).entries());obj.id=HR.uid('TH');const saved=HR.load(`${this.data.moduleId}-${f.sectionId}`,[]);saved.unshift(obj);HR.save(`${this.data.moduleId}-${f.sectionId}`,saved);this.rows[f.sectionId].unshift(obj);ERP.close('publicFormModal');e.currentTarget.reset();this.renderNavigation();this.renderSection(this.data.sections.find(x=>x.id===f.sectionId));ERP.toast('Registro guardado en modo demostración')},
  exportActive(){const s=this.data.sections.find(x=>x.id===this.active);ERP.csv(`${this.data.moduleId}-${s.id}.csv`,this.visibleRows(s))}
 };window.PublicHR=P;
})();
