document.addEventListener('DOMContentLoaded', async()=>{
  'use strict'; const data=await ATT.load('data.json','erp-attention-permissions-v22'); const save=()=>ATT.save('',data);
  const labels={manage_all:'Administración total',manage_appointments:'Gestionar citas',manage_attentions:'Gestionar atenciones',view_reports:'Consultar reportes',manage_visitors:'Gestionar visitantes',manage_queue:'Gestionar turnos',checkin_checkout:'Registrar ingreso/salida',view_own_visits:'Consultar visitas propias',view_audit:'Consultar auditoría'};
  function render(){
    const active=ATT.currentRole(data); metrics.innerHTML=[['users',data.roles.length,'Roles','Perfiles configurados'],['key-round',data.permissionMatrix.filter(i=>i.allowed).length,'Permisos','Autorizaciones activas'],['user-check',active,'Rol simulado','Vista actual'],['shield-check',data.roles.filter(i=>i.active!==false).length,'Roles activos','Disponibles para asignación']].map(x=>`<div class="att-kpi"><span class="att-kpi-icon"><i data-lucide="${x[0]}"></i></span><div class="att-kpi-copy"><span>${x[2]}</span><strong>${ATT.esc(x[1])}</strong><small>${x[3]}</small></div></div>`).join('');
    roleSelector.innerHTML=data.roles.filter(r=>r.active!==false).map(r=>`<option ${r.name===active?'selected':''}>${ATT.esc(r.name)}</option>`).join('');
    permissionTable.innerHTML=`<div class="att-table-wrap"><table class="att-table"><thead><tr><th>Rol</th><th>Permiso</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${data.permissionMatrix.map((p,i)=>`<tr><td class="permission-role"><strong>${ATT.esc(p.role)}</strong><small>${ATT.esc(data.roles.find(r=>r.name===p.role)?.description||'')}</small></td><td>${ATT.esc(labels[p.action]||p.action)}</td><td>${ATT.badge(p.allowed?'Permitido':'Bloqueado')}</td><td><button class="icon-btn" data-toggle="${i}" title="Cambiar"><i data-lucide="${p.allowed?'lock-open':'lock'}"></i></button></td></tr>`).join('')}</tbody></table></div>`;
    controlList.innerHTML=[['Separación de funciones','Quien administra datos no debe auditar sus propios cambios.'],['Mínimo privilegio','Cada perfil recibe solo los permisos necesarios.'],['Información protegida','Exportaciones y consultas sensibles quedan auditadas.'],['Revisión periódica','Los permisos deben revisarse ante cambios de cargo.']].map(x=>`<div class="att-item"><span class="att-item-icon"><i data-lucide="shield"></i></span><div><strong>${x[0]}</strong><span>${x[1]}</span></div></div>`).join(''); ATT.icons();
  }
  roleSelector.onchange=()=>{ATT.setRole(data,roleSelector.value);ATT.audit(data,'Permisos','Cambiar rol de simulación','Rol',roleSelector.value,'');save();render();ERP.toast(`Rol activo: ${roleSelector.value}`);};
  newPermission.onclick=()=>ATT.modal('Agregar permiso',[{name:'role',label:'Rol',type:'select',options:data.roles.map(r=>r.name)},{name:'action',label:'Acción',type:'select',options:Object.entries(labels).map(([value,label])=>({value,label}))},{name:'allowed',label:'Estado',type:'checkbox',checkboxLabel:'Permiso habilitado',value:true,full:true}],v=>{data.permissionMatrix.push({role:v.role,action:v.action,allowed:v.allowed==='true'});ATT.audit(data,'Permisos','Agregar permiso','Rol',v.role,v.action);save();render();});
  permissionTable.onclick=e=>{const b=e.target.closest('[data-toggle]');if(!b)return;const p=data.permissionMatrix[Number(b.dataset.toggle)];p.allowed=!p.allowed;ATT.audit(data,'Permisos','Cambiar permiso','Rol',p.role,`${p.action}:${p.allowed}`);save();render();}; render();
});
