document.addEventListener('DOMContentLoaded', async () => {
  'use strict';
  const data = await ATT.load('data.json', 'erp-attention-records-v17');
  const save = () => ATT.save('', data);
  ATT.insertLegalNotice('.page-heading');
  if (!document.getElementById('exportProtectedAttentions')) exportAttentions.insertAdjacentHTML('afterend','<button class="btn btn-secondary btn-sm" id="exportProtectedAttentions"><i data-lucide="lock-keyhole"></i> Base protegida</button>');

  function filtered(){const q=attentionSearch.value.trim().toLowerCase();return data.attentions.filter(i=>(!q||[i.person,i.document,i.service,i.outcome,i.staff,i.category,i.commitment].some(v=>String(v||'').toLowerCase().includes(q)))&&(!channelFilter.value||i.channel===channelFilter.value)&&(!statusFilter.value||i.status===statusFilter.value)).sort((a,b)=>`${b.date} ${b.time}`.localeCompare(`${a.date} ${a.time}`));}
  function render(){
    const rows=filtered();const open=data.attentions.filter(i=>!['Finalizada','Cerrada'].includes(i.status));const overdue=open.filter(i=>i.due&&i.due<(data.settings.currentDate||ATT.nowDate()));const rated=data.attentions.filter(i=>Number(i.rating));const average=rated.length?(rated.reduce((s,i)=>s+Number(i.rating),0)/rated.length).toFixed(1):'—';
    metrics.innerHTML=[['clipboard-list',data.attentions.length,'Atenciones','Registros acumulados'],['flag',open.length,'Compromisos abiertos','Pendientes o seguimiento'],['alarm-clock',overdue.length,'Seguimientos vencidos','Requieren actuación'],['star',average,'Satisfacción','Promedio registrado']].map(x=>`<div class="att-kpi"><span class="att-kpi-icon"><i data-lucide="${x[0]}"></i></span><div class="att-kpi-copy"><span>${x[2]}</span><strong>${x[1]}</strong><small>${x[3]}</small></div></div>`).join('');
    attentionTable.innerHTML=rows.length?`<div class="att-table-wrap"><table class="att-table"><thead><tr><th>Fecha</th><th>Usuario</th><th>Canal / servicio</th><th>Tipo</th><th>Resultado</th><th>Compromiso / seguimiento</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${rows.map(i=>`<tr><td><strong>${ATT.fmtDate(i.date)}</strong><small>${ATT.esc(i.time)}</small></td><td><strong>${ATT.esc(i.person)}</strong><small>${ATT.maskDocument(i.document)}</small></td><td>${ATT.esc(i.channel)}<small>${ATT.esc(i.service)}</small></td><td>${ATT.esc(i.category||i.requestType||'Orientación')}<small>${ATT.esc(i.staff)}</small></td><td><strong>${ATT.esc(i.outcome)}</strong></td><td>${ATT.esc(i.commitment||'Sin compromiso')}<small>${i.due?`Seguimiento: ${ATT.fmtDate(i.due)}`:'Sin fecha'}</small></td><td>${ATT.badge(i.status)}</td><td><div class="att-action-menu"><button class="icon-btn" data-view="${i.id}"><i data-lucide="eye"></i></button><button class="icon-btn" data-edit="${i.id}"><i data-lucide="pencil"></i></button>${!['Finalizada','Cerrada'].includes(i.status)?`<button class="icon-btn" data-close-attention="${i.id}"><i data-lucide="check-circle"></i></button>`:''}<button class="icon-btn" data-rate="${i.id}"><i data-lucide="star"></i></button></div></td></tr>`).join('')}</tbody></table></div>`:'<div class="att-empty">No hay atenciones para este filtro.</div>';ATT.icons();
  }
  function fields(item={}){return[{name:'person',label:'Nombre completo',value:item.person||'',required:true},{name:'document',label:'Documento',value:item.document||'',required:true},{name:'channel',label:'Canal',type:'select',value:item.channel||'Presencial',options:['Presencial','Telefónica','Virtual','Correo']},{name:'service',label:'Servicio',type:'select',value:item.service||'',options:data.services.filter(s=>s.active!==false).map(s=>s.name)},{name:'staff',label:'Responsable',type:'select',value:item.staff||'',options:data.staff.filter(s=>s.active!==false).map(s=>s.name)},{name:'category',label:'Tipo de atención',type:'select',value:item.category||item.requestType||'Orientación',options:['Orientación','Entrega de documentos','Seguimiento','Reunión','Atención a proveedor','Otra']},{name:'outcome',label:'Resultado',type:'textarea',value:item.outcome||'',full:true,required:true},{name:'commitment',label:'Compromiso o siguiente paso',type:'textarea',value:item.commitment||'',full:true},{name:'due',label:'Fecha de seguimiento',type:'date',value:item.due||''},{name:'status',label:'Estado',type:'select',value:item.status||'Finalizada',options:['Finalizada','Seguimiento','Pendiente','Cerrada']},{name:'privacyNoticeAccepted',label:'Privacidad',type:'checkbox',checkboxLabel:'Se informó la finalidad del tratamiento de los datos.',value:item.privacyNoticeAccepted!==false,required:true,full:true}];}
  function openForm(item=null){ATT.modal(item?'Editar atención':'Registrar atención',fields(item||{}),v=>{const payload={...v,privacyNoticeAccepted:v.privacyNoticeAccepted==='true',informationClass:data.settings.informationClass,retentionRule:data.settings.retentionRule};if(item)Object.assign(item,payload,{updatedAt:`${ATT.nowDate()} ${ATT.nowTime()}`});else data.attentions.push({...payload,id:ATT.uid('ATE'),date:data.settings.currentDate||ATT.nowDate(),time:ATT.nowTime(),rating:'',createdAt:`${ATT.nowDate()} ${ATT.nowTime()}`});const record=item||data.attentions.at(-1);ATT.upsertContact(data,v);if(v.commitment)ATT.notify(data,{title:'Compromiso de atención',message:`${v.person} · ${v.commitment}`,channel:'Notificación interna',recipient:v.staff,status:'Pendiente',relatedId:record.id});ATT.audit(data,'Atenciones',item?'Editar atención':'Crear atención','Atención',record.id,v.category);save();render();ERP.toast('Atención guardada');});}
  function detail(item){ATT.detail(item.id,`<div class="att-grid att-grid-2"><div><strong>Usuario</strong><p>${ATT.esc(item.person)} · ${ATT.maskDocument(item.document)}</p></div><div><strong>Atención</strong><p>${ATT.fmtDate(item.date)} · ${item.time} · ${ATT.esc(item.channel)}</p></div><div><strong>Tipo</strong><p>${ATT.esc(item.category||item.requestType||'Orientación')}</p></div><div><strong>Responsable</strong><p>${ATT.esc(item.staff)}</p></div><div><strong>Resultado</strong><p>${ATT.esc(item.outcome)}</p></div><div><strong>Compromiso</strong><p>${ATT.esc(item.commitment||'Sin compromiso')}</p></div><div><strong>Seguimiento</strong><p>${item.due?ATT.fmtDate(item.due):'No programado'}</p></div><div><strong>Estado</strong><p>${ATT.esc(item.status)}</p></div></div><div class="att-audit-mini"><i data-lucide="shield-check"></i> ${ATT.esc(item.informationClass||data.settings.informationClass)}</div>`,`<button class="btn btn-primary" data-detail-edit="${item.id}">Editar</button>`);}
  newAttention.onclick=()=>openForm();attentionSearch.oninput=render;channelFilter.onchange=render;statusFilter.onchange=render;
  exportAttentions.onclick=()=>ATT.exportPublic('reporte-publico-atenciones-anonimizado.csv',data.attentions,[{label:'Fecha',key:'date'},{label:'Canal',key:'channel'},{label:'Servicio',key:'service'},{label:'Tipo',value:i=>i.category||i.requestType||'Orientación'},{label:'Estado',key:'status'},{label:'Seguimiento',key:'due'},{label:'Calificación',key:'rating'}]);
  document.getElementById('exportProtectedAttentions').onclick=()=>ATT.exportProtected(data,'registro-atenciones-protegido.csv',data.attentions,'Atenciones');
  document.addEventListener('click',e=>{const v=e.target.closest('[data-view]');if(v){const i=data.attentions.find(x=>x.id===v.dataset.view);if(i)detail(i);}const ed=e.target.closest('[data-edit],[data-detail-edit]');if(ed){ERP.close('attDetailModal');const i=data.attentions.find(x=>x.id===(ed.dataset.edit||ed.dataset.detailEdit));if(i)openForm(i);}const c=e.target.closest('[data-close-attention]');if(c){const i=data.attentions.find(x=>x.id===c.dataset.closeAttention);if(!i)return;i.status='Finalizada';i.closedAt=`${ATT.nowDate()} ${ATT.nowTime()}`;ATT.audit(data,'Atenciones','Cerrar atención','Atención',i.id,i.service);save();render();}const r=e.target.closest('[data-rate]');if(r){const i=data.attentions.find(x=>x.id===r.dataset.rate);ATT.modal('Registrar satisfacción',[{name:'rating',label:'Calificación',type:'select',value:i.rating||'5',options:['1','2','3','4','5']},{name:'ratingComment',label:'Comentario',type:'textarea',value:i.ratingComment||'',full:true}],v=>{i.rating=Number(v.rating);i.ratingComment=v.ratingComment;ATT.audit(data,'Atenciones','Registrar satisfacción','Atención',i.id,v.rating);save();render();});}});render();
});
