(function(){
 const KEY='erp-itsm-tickets-v4';
 const OVERRIDES='erp-itsm-overrides-v4';
 const ITSM={
  async seed(path){const seed=await ERP.fetchJSON(path,{tickets:[]});let rows=JSON.parse(localStorage.getItem(KEY)||'null');if(!Array.isArray(rows)){rows=seed.tickets||[];localStorage.setItem(KEY,JSON.stringify(rows));}return rows;},
  tickets(){return JSON.parse(localStorage.getItem(KEY)||'[]');},
  save(rows){localStorage.setItem(KEY,JSON.stringify(rows));window.dispatchEvent(new CustomEvent('itsm:tickets'));},
  create(payload){const rows=this.tickets();const type=payload.type==='Incidente'?'INC':'REQ';const max=rows.map(x=>Number(String(x.id).split('-').pop())).filter(Number.isFinite).reduce((a,b)=>Math.max(a,b),1087);const now=new Date();const priority=this.priority(payload.impact,payload.urgency);const hours={P1:2,P2:5,P3:24,P4:48}[priority];const t={id:`${type}-${now.getFullYear()}-${max+1}`,status:'Nuevo',channel:'Portal',agent:'Sin asignar',group:'Mesa de Servicios TIC',created:now.toISOString(),responseDue:new Date(now.getTime()+({P1:.25,P2:.5,P3:4,P4:8}[priority])*3600000).toISOString(),resolutionDue:new Date(now.getTime()+hours*3600000).toISOString(),sla:`SLA ${priority}`,tags:[],timeline:[{title:'Caso radicado',meta:new Intl.DateTimeFormat('es-CO',{dateStyle:'medium',timeStyle:'short'}).format(now)+' · Portal institucional'}],...payload,priority};rows.unshift(t);this.save(rows);return t;},
  update(id,patch,event){const rows=this.tickets(),i=rows.findIndex(x=>x.id===id);if(i<0)return null;rows[i]={...rows[i],...patch};if(event){rows[i].timeline=rows[i].timeline||[];rows[i].timeline.push({title:event,meta:new Intl.DateTimeFormat('es-CO',{dateStyle:'medium',timeStyle:'short'}).format(new Date())+' · Usuario TIC'});}this.save(rows);return rows[i];},
  priority(impact='Bajo',urgency='Baja'){const v={Bajo:1,Medio:2,Alto:3},score=v[impact]+v[urgency];return score>=6?'P1':score>=5?'P2':score>=3?'P3':'P4';},
  priorityTone(p){return {P1:'p1',P2:'p2',P3:'p3',P4:'p4'}[p]||'p4';},
  statusTone(s){if(['Resuelto','Cerrado','Implementado','Publicado','Operativo'].includes(s))return 'status-success';if(['En proceso','En diagnóstico','En implementación','Investigación'].includes(s))return 'status-info';if(['Esperando usuario','Pendiente aprobación','Programado','Asignado'].includes(s))return 'status-warning';if(['Vencido','Fallido','Suspendido'].includes(s))return 'status-danger';return 'status-neutral';},
  formatDate(v){if(!v)return '—';return new Intl.DateTimeFormat('es-CO',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v));},
  remaining(v){if(!v)return 'Sin objetivo';const ms=new Date(v)-new Date();const abs=Math.abs(ms),h=Math.floor(abs/3600000),m=Math.floor((abs%3600000)/60000);return `${ms<0?'-':''}${h}h ${m}m`;},
  slaClass(v){const ms=new Date(v)-new Date();return ms<0?'breach':ms<7200000?'risk':'';},
  initials(n=''){return n.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();},
  exportCSV(filename,rows){ERP.csv(filename,rows);},
  openTicket(id,containerId='ticketDetail',drawerId='ticketDrawer',backdropId='ticketDrawerBackdrop'){
   const t=this.tickets().find(x=>x.id===id),el=document.getElementById(containerId);if(!t||!el)return;
   el.innerHTML=`<div class="ticket-detail-head"><div style="display:flex;justify-content:space-between;gap:10px"><strong class="ticket-code">${t.id}</strong><span class="priority-pill ${this.priorityTone(t.priority)}">${t.priority}</span></div><h2>${t.title}</h2><p>${t.requester} · ${t.office}</p></div><div class="fact-grid" style="margin-top:14px"><div class="fact"><span>Estado</span><strong>${t.status}</strong></div><div class="fact"><span>Responsable</span><strong>${t.agent}</strong></div><div class="fact"><span>Grupo</span><strong>${t.group}</strong></div><div class="fact"><span>Servicio</span><strong>${t.service}</strong></div><div class="fact"><span>Activo / CI</span><strong>${t.asset||'No relacionado'}</strong></div><div class="fact"><span>SLA de resolución</span><strong class="sla-clock ${this.slaClass(t.resolutionDue)}">${this.remaining(t.resolutionDue)}</strong></div></div><div class="card" style="margin-top:14px"><div class="card-body"><strong>Descripción</strong><p style="color:var(--muted)">${t.description}</p></div></div><div class="section-head"><div><h2>Actividad</h2><p>Historial inalterable del caso</p></div></div><div class="activity-thread">${(t.timeline||[]).map(a=>`<div class="activity-item"><span class="activity-dot"></span><strong>${a.title}</strong><span>${a.meta}</span></div>`).join('')}</div><div class="heading-actions"><button class="btn btn-primary" onclick="ITSM.advance('${t.id}')"><i data-lucide="arrow-right"></i> Avanzar estado</button><button class="btn btn-secondary" onclick="ITSM.assign('${t.id}')"><i data-lucide="users"></i> Autoasignar</button><button class="btn btn-secondary" onclick="ITSM.resolve('${t.id}')"><i data-lucide="circle-check"></i> Resolver</button></div>`;
   ERP.open(backdropId);document.getElementById(drawerId)?.classList.remove('hidden');ERP.refreshIcons();
  },
  closeDrawer(){ERP.close('ticketDrawerBackdrop');document.getElementById('ticketDrawer')?.classList.add('hidden');},
  advance(id){const t=this.tickets().find(x=>x.id===id);if(!t)return;const flow=['Nuevo','Asignado','En diagnóstico','En proceso','Esperando usuario','Resuelto','Cerrado'];const next=flow[Math.min(Math.max(flow.indexOf(t.status),0)+1,flow.length-1)];this.update(id,{status:next},`Estado actualizado a ${next}`);this.openTicket(id);document.dispatchEvent(new Event('itsm:refresh'));ERP.toast(`Caso ${id}: ${next}`);},
  assign(id){this.update(id,{agent:'Juan Esteban Pérez',group:'Mesa de Servicios TIC',status:'Asignado'},'Caso asignado a Juan Esteban Pérez');this.openTicket(id);document.dispatchEvent(new Event('itsm:refresh'));ERP.toast('Responsable asignado');},
  resolve(id){this.update(id,{status:'Resuelto'},'Solución registrada y enviada al usuario');this.openTicket(id);document.dispatchEvent(new Event('itsm:refresh'));ERP.toast('Caso marcado como resuelto');}
 };
 window.ITSM=ITSM;
})();
