let TH={data:null,people:[]};
document.addEventListener('DOMContentLoaded',async()=>{
 TH.data=await ERP.fetchJSON('data.json',{metrics:[],people:[],novelties:[],alerts:[]});
 const saved=JSON.parse(localStorage.getItem('erp-th-novelties')||'[]'); TH.data.novelties=[...saved,...TH.data.novelties]; TH.people=TH.data.people;
 document.getElementById('metrics').innerHTML=TH.data.metrics.map(m=>`<article class="card metric-card ${m.tone||''}"><div class="metric-copy"><span>${m.label}</span><strong>${m.value}</strong><small>${m.hint}</small></div><div class="metric-icon"><i data-lucide="${m.icon}"></i></div></article>`).join('');
 document.getElementById('alerts').innerHTML=TH.data.alerts.map(a=>`<div class="alert-line"><div><strong>${a.title}</strong><div style="color:var(--muted);font-size:12px">${a.detail}</div></div><span class="status ${a.level==='Alta'?'status-danger':'status-warning'}">${a.level}</span></div>`).join('');
 renderPeople();renderNovelties(); ERP.refreshIcons();
 ['search','typeFilter','statusFilter'].forEach(id=>document.getElementById(id).addEventListener('input',renderPeople));
 document.getElementById('exportBtn').addEventListener('click',()=>ERP.csv('talento-humano.csv',TH.people.map(p=>({Código:p.id,Nombre:p.name,Documento:p.document,Vinculación:p.type,Cargo:p.role,Dependencia:p.office,Estado:p.status,Correo:p.email}))));
 document.getElementById('newNoveltyForm').addEventListener('submit',saveNovelty);
});
function renderPeople(){const q=document.getElementById('search').value.toLowerCase(),type=document.getElementById('typeFilter').value,status=document.getElementById('statusFilter').value; const rows=TH.people.filter(p=>(p.name+' '+p.document+' '+p.role+' '+p.office).toLowerCase().includes(q)&&(!type||p.type===type)&&(!status||p.status===status));document.getElementById('peopleBody').innerHTML=rows.length?rows.map(p=>`<tr data-id="${p.id}"><td><div class="table-person"><div class="avatar">${ERP.initials(p.name)}</div><div><strong>${p.name}</strong><span>${p.email}</span></div></div></td><td>${p.type}</td><td>${p.role}<div style="color:var(--muted);font-size:11px">${p.office}</div></td><td><span class="status ${p.status==='Activo'?'status-success':p.status==='Vacaciones'?'status-info':'status-warning'}">${p.status}</span></td><td><div style="min-width:100px"><div class="progress ${p.documents<80?'danger':p.documents<95?'warning':'success'}"><span style="width:${p.documents}%"></span></div><small>${p.documents}%</small></div></td><td><button class="btn btn-secondary btn-sm" onclick="openPerson('${p.id}')">Ver ficha</button></td></tr>`).join(''):`<tr><td colspan="6"><div class="empty-state">No se encontraron personas.</div></td></tr>`;ERP.refreshIcons()}
function renderNovelties(){document.getElementById('noveltiesBody').innerHTML=TH.data.novelties.map(n=>`<tr><td><strong>${n.id}</strong></td><td>${n.person}</td><td>${n.type}</td><td>${ERP.formatDate(n.from)} ${n.to!==n.from?'– '+ERP.formatDate(n.to):''}</td><td><span class="status ${n.status==='Aprobada'?'status-success':n.status==='Pendiente'?'status-warning':'status-info'}">${n.status}</span></td></tr>`).join('')}
function openPerson(id){const p=TH.people.find(x=>x.id===id);if(!p)return;document.getElementById('personDrawerContent').innerHTML=`<div class="person-summary"><div class="avatar">${ERP.initials(p.name)}</div><div><span class="status status-success">${p.status}</span><h2>${p.name}</h2><p>${p.role} · ${p.office}</p></div></div><div class="detail-grid"><div class="detail-item"><span>Documento</span><strong>${p.document}</strong></div><div class="detail-item"><span>Vinculación</span><strong>${p.type}</strong></div><div class="detail-item"><span>Correo</span><strong>${p.email}</strong></div><div class="detail-item"><span>Contacto</span><strong>${p.phone}</strong></div><div class="detail-item"><span>Fecha de ingreso</span><strong>${ERP.formatDate(p.start)}</strong></div><div class="detail-item"><span>Documentación</span><strong>${p.documents}% completa</strong></div></div><div class="card" style="margin-top:18px"><div class="card-header"><h3>Acciones rápidas</h3></div><div class="card-body heading-actions"><button class="btn btn-secondary btn-sm"><i data-lucide="folder-open"></i> Expediente</button><button class="btn btn-secondary btn-sm"><i data-lucide="file-text"></i> Certificado</button><button class="btn btn-secondary btn-sm"><i data-lucide="calendar-plus"></i> Asignar actividad</button></div></div>`;ERP.open('personDrawerBackdrop');document.getElementById('personDrawer').classList.remove('hidden');ERP.refreshIcons()}
function closePerson(){ERP.close('personDrawerBackdrop');document.getElementById('personDrawer').classList.add('hidden')}
function saveNovelty(e){e.preventDefault();const f=new FormData(e.target);const n={id:`NOV-2026-${String(TH.data.novelties.length+44).padStart(3,'0')}`,person:f.get('person'),type:f.get('type'),from:f.get('from'),to:f.get('to'),status:'Radicada'};const saved=JSON.parse(localStorage.getItem('erp-th-novelties')||'[]');saved.unshift(n);localStorage.setItem('erp-th-novelties',JSON.stringify(saved));TH.data.novelties.unshift(n);renderNovelties();ERP.close('noveltyModal');e.target.reset();ERP.toast('Novedad radicada en modo demostración')}
window.openPerson=openPerson;window.closePerson=closePerson;
