
(function(){
  const S={data:null,slug:null,records:[],filtered:[]};
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const statusClass=v=>{const s=String(v||'').toLowerCase();if(/alto|crítico|extremo|vencid|no conform|pendiente|sin control|suspendido/.test(s))return 'status-danger';if(/medio|parcial|revisión|evaluación|plan|seguimiento|riesgo|observación|preparación|informe|brecha/.test(s))return 'status-warning';if(/cumple|vigente|cerrad|controlado|competente|aprobado|implementado|probado|meta|eficaz|gestionado|estable/.test(s))return 'status-success';return 'status-info'};
  const loadLocal=()=>{try{return JSON.parse(localStorage.getItem(`sig-${S.slug}-records`)||'null')}catch{return null}};
  const saveLocal=()=>localStorage.setItem(`sig-${S.slug}-records`,JSON.stringify(S.records));
  async function init(slug){S.slug=slug;S.data=await ERP.fetchJSON('data.json',{});S.records=loadLocal()||S.data.records||[];renderMetrics();buildFilters();render();bind();ERP.refreshIcons()}
  function renderMetrics(){const el=document.getElementById('sigMetrics');if(!el)return;el.innerHTML=(S.data.metrics||[]).map(m=>`<article class="sig-kpi ${m.tone||''}"><div class="sig-kpi-icon"><i data-lucide="${esc(m.icon||'gauge')}"></i></div><div class="sig-kpi-copy"><span>${esc(m.label)}</span><strong>${esc(m.value)}</strong><small>${esc(m.hint||'')}</small></div></article>`).join('')}
  function buildFilters(){const box=document.getElementById('dynamicFilters');if(!box)return;box.innerHTML=(S.data.filters||[]).map((f,i)=>{const vals=[...new Set(S.records.map(r=>r[f.key]).filter(Boolean))];return `<select data-filter="${esc(f.key)}" aria-label="${esc(f.label)}"><option value="">${esc(f.label)}: Todos</option>${vals.map(v=>`<option>${esc(v)}</option>`).join('')}</select>`}).join('')}
  function currentRecords(){const q=(document.getElementById('sigSearch')?.value||'').toLowerCase();const filters=[...document.querySelectorAll('[data-filter]')];return S.records.filter(r=>{const text=Object.values(r).join(' ').toLowerCase();return (!q||text.includes(q))&&filters.every(f=>!f.value||String(r[f.dataset.filter])===f.value)})}
  function render(){S.filtered=currentRecords();const mode=S.data.mode||'table';if(mode==='standards')renderStandards();else if(mode==='requirements')renderRequirements();else if(mode==='processes')renderProcesses();else if(mode==='risk')renderRisk();else if(mode==='audit')renderAudit();else if(mode==='review')renderReview();else if(['special','isms','continuity','integrity'].includes(mode))renderSpecial();else if(mode==='capa')renderCapa();else renderTable();ERP.refreshIcons()}
  function renderTable(){const el=document.getElementById('sigContent');if(!el)return;const cols=S.data.columns||[];el.innerHTML=`<div class="sig-table-wrap"><table class="sig-table"><thead><tr>${cols.map(c=>`<th>${esc(c.label)}</th>`).join('')}<th>Acciones</th></tr></thead><tbody>${S.filtered.length?S.filtered.map(r=>`<tr>${cols.map(c=>`<td>${cell(r,c)}</td>`).join('')}<td>${actions(r)}</td></tr>`).join(''):`<tr><td colspan="${cols.length+1}"><div class="sig-empty">No hay registros que coincidan con los filtros.</div></td></tr>`}</tbody></table></div>`}
  function cell(r,c){const v=r[c.key];if(c.type==='status')return `<button class="sig-status-btn" data-cycle="${esc(r.id)}"><span class="status ${statusClass(v)}">${esc(v)}</span></button>`;if(c.type==='progress'){const n=Math.max(0,Math.min(100,Number(v)||0));return `<div class="sig-progress"><div class="sig-progress-line"><span style="width:${n}%"></span></div><small>${n}%</small></div>`}if(c.type==='date')return esc(ERP.formatDate(v));if(c.type==='badge')return `<span class="sig-badge">${esc(v)}</span>`;if(c.key==='name'||c.key==='finding'||c.key==='action'||c.key==='risk'||c.key==='decision'||c.key==='change'||c.key==='service'||c.key==='asset'||c.key==='subject')return `<div class="sig-cell-main"><strong>${esc(v)}</strong>${r.description?`<small>${esc(r.description)}</small>`:''}</div>`;return esc(v)}
  function actions(r){return `<div class="sig-row-actions"><button class="icon-btn" data-view="${esc(r.id)}" title="Ver detalle"><i data-lucide="eye"></i></button><button class="icon-btn" data-edit="${esc(r.id)}" title="Editar"><i data-lucide="pencil"></i></button></div>`}
  function renderStandards(){const el=document.getElementById('sigContent');el.innerHTML=`<div class="standard-grid">${S.filtered.map(r=>`<article class="standard-card"><div class="standard-top"><div class="standard-code"><i data-lucide="badge-check"></i><div><strong>${esc(r.code)}</strong><span>${esc(r.version)}</span></div></div><button class="sig-status-btn" data-cycle="${esc(r.id)}"><span class="status ${statusClass(r.status)}">${esc(r.status)}</span></button></div><h3>${esc(r.name)}</h3><p>${esc(r.scope)}</p><div class="standard-meta"><div><span>Responsable</span><strong>${esc(r.owner)}</strong></div><div><span>Certificación</span><strong>${esc(r.certifiable)}</strong></div><div><span>Transición</span><strong>${esc(r.transition)}</strong></div><div><span>Preparación</span><strong>${esc(r.progress)}%</strong></div></div><div class="standard-foot"><div class="standard-progress sig-progress-line"><span style="width:${Number(r.progress)||0}%"></span></div><button class="btn btn-secondary btn-sm" data-view="${esc(r.id)}">Abrir</button></div></article>`).join('')}</div>`}
  function renderRequirements(){const el=document.getElementById('sigContent');el.innerHTML=`<div class="req-list">${S.filtered.map(r=>`<article class="req-card"><div class="req-clause">${esc(r.clause)}</div><div class="req-copy"><strong>${esc(r.title)}</strong><p>${esc(r.evidence)}</p><div class="sig-chip-list">${(r.standards||[]).slice(0,4).map(s=>`<span class="sig-badge">${esc(s)}</span>`).join('')}${(r.standards||[]).length>4?`<span class="sig-badge">+${r.standards.length-4}</span>`:''}</div></div><div class="req-evidence"><span>Responsable</span><strong>${esc(r.owner)}</strong><div style="margin-top:5px"><span class="status ${statusClass(r.status)}">${esc(r.status)}</span></div></div><div class="req-score"><strong>${esc(r.coverage)}%</strong><div class="sig-progress-line"><span style="width:${r.coverage}%"></span></div><button class="btn btn-secondary btn-sm" data-view="${esc(r.id)}" style="margin-top:7px">Evidencias</button></div></article>`).join('')}</div>`}
  function renderProcesses(){const categories=['Estratégico','Misional','Apoyo','Evaluación'];const el=document.getElementById('sigContent');el.innerHTML=`<div class="process-lanes">${categories.map(cat=>{const rows=S.filtered.filter(r=>r.category===cat);return `<section class="process-lane"><div class="process-lane-head"><strong>${cat}</strong><span class="sig-badge">${rows.length} procesos</span></div><div class="process-lane-body">${rows.map(r=>`<article class="process-card" data-view="${esc(r.id)}"><strong>${esc(r.name)}</strong><p>${esc(r.owner)}</p><div class="sig-progress-line"><span style="width:${r.maturity}%"></span></div><div class="process-foot"><span>${r.maturity}% madurez</span><span class="status ${statusClass(r.status)}">${esc(r.status)}</span></div></article>`).join('')}</div></section>`}).join('')}</div>`}
  function riskLevel(p,i){const n=p*i;return n>=20?'extreme':n>=12?'high':n>=5?'medium':'low'}
  function renderRisk(){const counts={};S.filtered.forEach(r=>{if(Number(r.probability)&&Number(r.impact)){const k=`${r.probability}-${r.impact}`;counts[k]=(counts[k]||0)+1}});let matrix='';for(let p=5;p>=1;p--){matrix+=`<div class="risk-axis">${p}</div>`;for(let i=1;i<=5;i++){const k=`${p}-${i}`;matrix+=`<div class="risk-cell ${riskLevel(p,i)}" title="Probabilidad ${p} · Impacto ${i}">${counts[k]?`<span class="risk-count">${counts[k]}</span>`:''}</div>`}}matrix+='<div></div>';for(let i=1;i<=5;i++)matrix+=`<div class="risk-axis">${i}</div>`;const el=document.getElementById('sigContent');el.innerHTML=`<div class="risk-layout"><aside class="sig-card"><div class="sig-card-head"><div><h3>Matriz 5 × 5</h3><p>Probabilidad por impacto</p></div></div><div class="sig-card-body"><div class="risk-matrix">${matrix}</div><div class="risk-legend"><span><i style="background:#e9f7f1"></i>Bajo</span><span><i style="background:#fff6e5"></i>Medio</span><span><i style="background:#fff0f2"></i>Alto</span><span><i style="background:#a52f3e"></i>Extremo</span></div></div></aside><div>${tableHTML()}</div></div>`}
  function tableHTML(){const cols=S.data.columns?.length?S.data.columns:[{'key':'id','label':'Código'},{'key':'risk','label':'Riesgo'},{'key':'system','label':'Sistema','type':'badge'},{'key':'level','label':'Nivel','type':'status'},{'key':'owner','label':'Responsable'},{'key':'progress','label':'Avance','type':'progress'},{'key':'status','label':'Estado','type':'status'}];return `<div class="sig-table-wrap"><table class="sig-table"><thead><tr>${cols.map(c=>`<th>${esc(c.label)}</th>`).join('')}<th>Acciones</th></tr></thead><tbody>${S.filtered.map(r=>`<tr>${cols.map(c=>`<td>${cell(r,c)}</td>`).join('')}<td>${actions(r)}</td></tr>`).join('')}</tbody></table></div>`}
  function renderAudit(){const stages=[['Programada','Definir alcance y criterios'],['Preparación','Equipo, plan y listas'],['Ejecución','Entrevistas y evidencias'],['Informe','Hallazgos y cierre']];const el=document.getElementById('sigContent');el.innerHTML=`<div class="audit-timeline">${stages.map(([s,d])=>{const n=S.records.filter(r=>r.status===s).length;return `<article class="audit-stage"><span>${s}</span><strong>${n} auditorías</strong><p>${d}</p></article>`}).join('')}</div>${tableHTML()}`}
  function renderReview(){const agenda=S.data.extra?.agenda||[];const el=document.getElementById('sigContent');el.innerHTML=`<div class="review-agenda">${agenda.map(a=>`<article class="review-item"><strong>${esc(a.title)}</strong><div class="sig-progress-line"><span style="width:${a.ready}%"></span></div><small>${a.ready}% preparado</small></article>`).join('')}</div>${tableHTML()}`}
  function renderSpecial(){const label=S.data.extra?.specialTitle||'Registro especializado';const el=document.getElementById('sigContent');el.innerHTML=`<div class="special-summary"><article class="special-box"><span>Vista activa</span><strong>${esc(label)}</strong></article><article class="special-box"><span>Registros visibles</span><strong>${S.filtered.length}</strong></article><article class="special-box"><span>Actualización</span><strong>Seguimiento continuo</strong></article><article class="special-box"><span>Integración</span><strong>Matriz SIG común</strong></article></div>${tableHTML()}`}
  function renderCapa(){renderTable()}
  function bind(){document.getElementById('sigSearch')?.addEventListener('input',render);document.getElementById('dynamicFilters')?.addEventListener('change',render);document.getElementById('exportBtn')?.addEventListener('click',()=>ERP.csv(`sig-${S.slug}.csv`,S.filtered));document.getElementById('newRecordBtn')?.addEventListener('click',()=>openForm());document.getElementById('resetBtn')?.addEventListener('click',()=>{localStorage.removeItem(`sig-${S.slug}-records`);S.records=[...(S.data.records||[])];buildFilters();render();ERP.toast('Datos de demostración restaurados')});document.addEventListener('click',e=>{const cyc=e.target.closest('[data-cycle]');if(cyc)cycle(cyc.dataset.cycle);const view=e.target.closest('[data-view]');if(view)showDetail(view.dataset.view);const edit=e.target.closest('[data-edit]');if(edit)openForm(edit.dataset.edit)});document.getElementById('recordForm')?.addEventListener('submit',saveForm)}
  function cycle(id){const r=S.records.find(x=>String(x.id)===String(id));if(!r)return;const opts=S.data.extra?.statusOptions||['Pendiente','En proceso','Cerrado'];const current=r.status||r.class||r.impact||'';const idx=opts.indexOf(current);r.status=opts[(idx+1)%opts.length];saveLocal();render();ERP.toast(`Estado actualizado: ${r.status}`)}
  function showDetail(id){const r=S.records.find(x=>String(x.id)===String(id));if(!r)return;const body=document.getElementById('detailBody');if(body){body.innerHTML=`<div class="sig-grid sig-grid-2">${Object.entries(r).filter(([k])=>!['id'].includes(k)).map(([k,v])=>`<div class="special-box"><span>${esc(k.replaceAll('_',' '))}</span><strong>${Array.isArray(v)?esc(v.join(', ')):esc(v)}</strong></div>`).join('')}</div>`;document.getElementById('detailTitle').textContent=r.name||r.risk||r.finding||r.action||r.service||r.asset||r.subject||r.id;ERP.open('detailModal')}}
  function openForm(id){const modal=document.getElementById('recordModal');if(!modal)return;const r=id?S.records.find(x=>String(x.id)===String(id)):null;const fields=S.data.form||[];document.getElementById('recordModalTitle').textContent=r?'Editar registro':'Nuevo registro';document.getElementById('recordId').value=r?.id||'';document.getElementById('formFields').innerHTML=fields.map(f=>{const val=r?.[f.name]??'';const full=f.type==='textarea'?' full':'';let input='';if(f.type==='select')input=`<select name="${esc(f.name)}" ${f.required?'required':''}><option value="">Seleccione</option>${(f.options||[]).map(o=>`<option ${String(o)===String(val)?'selected':''}>${esc(o)}</option>`).join('')}</select>`;else if(f.type==='textarea')input=`<textarea name="${esc(f.name)}" ${f.required?'required':''}>${esc(val)}</textarea>`;else input=`<input name="${esc(f.name)}" type="${esc(f.type||'text')}" value="${esc(val)}" ${f.required?'required':''}>`;return `<div class="sig-form-group${full}"><label>${esc(f.label)}</label>${input}</div>`}).join('');ERP.open('recordModal')}
  function saveForm(e){e.preventDefault();const fd=new FormData(e.target),id=document.getElementById('recordId').value;let r=id?S.records.find(x=>String(x.id)===String(id)):null;if(!r){r={id:`${S.slug.slice(0,4).toUpperCase()}-${Date.now().toString(36).toUpperCase()}`,status:S.data.extra?.statusOptions?.[0]||'Registrado',progress:0};S.records.unshift(r)}for(const f of S.data.form||[])r[f.name]=fd.get(f.name);if(r.probability&&r.impact){const n=Number(r.probability)*Number(r.impact);r.level=n>=20?'Extremo':n>=12?'Alto':n>=5?'Medio':'Bajo'}saveLocal();buildFilters();render();ERP.close('recordModal');ERP.toast(id?'Registro actualizado':'Registro creado');e.target.reset()}
  window.SIGModule={init};
})();
