document.addEventListener('DOMContentLoaded', async()=>{
  'use strict';
  const data=await ATT.load('data.json','erp-attention-public-v22');
  const save=()=>ATT.save('',data);
  const state={step:1,service:null,date:'',time:'',values:{}};
  const content=document.getElementById('bookingContent');
  const today=ATT.nowDate();

  function modalities(service){return String(service.modality||'Presencial').split('/').map(x=>x.trim()).filter(Boolean);}
  function availableSlots(date,service){
    if(!date||!service)return[];
    const slots=[];const open=ATT.minutes(data.schedule?.open||data.settings.open||'08:00');const close=ATT.minutes(data.schedule?.close||data.settings.close||'17:00');const lunchStart=ATT.minutes(data.schedule?.lunchStart||'12:00');const lunchEnd=ATT.minutes(data.schedule?.lunchEnd||'13:30');
    for(let m=open;m+Number(service.duration||30)<=close;m+=30){
      if(m<lunchEnd&&m+Number(service.duration||30)>lunchStart)continue;
      const h=`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;const end=ATT.addMinutes(h,service.duration||30);
      const busy=data.appointments.some(a=>a.date===date&&a.host===(state.values.host||a.host)&&!['Cancelada','Ausente'].includes(a.status)&&ATT.minutes(h)<ATT.minutes(a.end)&&ATT.minutes(end)>ATT.minutes(a.time));
      if(!busy)slots.push({time:h,end});
    }
    return slots;
  }
  function setStep(n){state.step=n;document.querySelectorAll('.step').forEach((b,i)=>{b.classList.toggle('active',i+1===n);b.classList.toggle('complete',i+1<n)});render();}
  function serviceStep(){content.innerHTML=`<div class="booking-content"><div class="booking-title"><h2>¿Qué atención necesitas?</h2><p>Selecciona el servicio. La duración y modalidad se aplicarán automáticamente.</p></div><div class="service-grid">${data.services.filter(s=>s.active!==false).map((s,i)=>`<button class="service-option${state.service?.id===s.id?' active':''}" data-service="${s.id}"><span><i data-lucide="${['calendar-check','message-circle-question','files','search-check','handshake'][i%5]}"></i></span><h3>${ATT.esc(s.name)}</h3><p>${ATT.esc(s.description||'Atención programada por la Secretaría General.')}</p><footer><b>${s.duration} min</b><em>${ATT.esc(s.modality)}</em></footer></button>`).join('')}</div><div class="booking-actions"><span></span><button class="public-btn" id="continueService" ${state.service?'':'disabled'}>Continuar</button></div></div>`;ATT.icons();content.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>{state.service=data.services.find(s=>s.id===b.dataset.service);state.values.service=state.service.name;state.values.host=data.staff.find(x=>x.active!==false)?.name||'';render();});document.getElementById('continueService').onclick=()=>setStep(2);}
  function dateStep(){const min=today;const slots=availableSlots(state.date,state.service);content.innerHTML=`<div class="booking-content"><div class="booking-title"><h2>Elige fecha y hora</h2><p>${ATT.esc(state.service.name)} · ${state.service.duration} minutos</p></div><div class="date-row"><label class="public-form"><span>Fecha disponible</span><input id="bookingDate" type="date" min="${min}" value="${state.date}"></label><div><strong style="font-size:10px">Horarios disponibles</strong><div class="slot-grid" style="margin-top:8px">${slots.length?slots.map(s=>`<button class="slot${state.time===s.time?' active':''}" data-time="${s.time}" data-end="${s.end}">${s.time}</button>`).join(''):'<div class="appointment-result">Selecciona una fecha para consultar horarios.</div>'}</div></div></div><div class="booking-actions"><button class="public-btn secondary" id="backService">Atrás</button><button class="public-btn" id="continueDate" ${state.time?'':'disabled'}>Continuar</button></div></div>`;document.getElementById('bookingDate').onchange=e=>{state.date=e.target.value;state.time='';render();};content.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{state.time=b.dataset.time;state.values.end=b.dataset.end;render();});document.getElementById('backService').onclick=()=>setStep(1);document.getElementById('continueDate').onclick=()=>setStep(3);}
  function dataStep(){content.innerHTML=`<div class="booking-content"><div class="booking-title"><h2>Datos de la cita</h2><p>${ATT.fmtDate(state.date)} · ${state.time} · ${ATT.esc(state.service.name)}</p></div><form id="publicBookingForm" class="public-form"><label>Nombre completo<input name="person" required value="${ATT.esc(state.values.person||'')}"></label><label>Documento<input name="document" required value="${ATT.esc(state.values.document||'')}"></label><label>Teléfono<input name="phone" required value="${ATT.esc(state.values.phone||'')}"></label><label>Correo electrónico<input name="email" type="email" required value="${ATT.esc(state.values.email||'')}"></label><label>Modalidad<select name="modality">${modalities(state.service).map(m=>`<option>${ATT.esc(m)}</option>`).join('')}</select></label><label>Responsable<select name="host">${data.staff.filter(s=>s.active!==false).map(s=>`<option>${ATT.esc(s.name)}</option>`).join('')}</select></label><label class="full">Observación breve<textarea name="notes" placeholder="Información necesaria para preparar la cita. No incluya datos sensibles."></textarea></label><label class="privacy-check full"><input name="privacy" type="checkbox" required><span>He leído el aviso de privacidad y autorizo el uso de estos datos exclusivamente para gestionar la cita, la llegada y la atención.</span></label></form><div class="booking-actions"><button class="public-btn secondary" id="backDate">Atrás</button><button class="public-btn" id="confirmBooking">Confirmar cita</button></div></div>`;document.getElementById('backDate').onclick=()=>setStep(2);document.getElementById('confirmBooking').onclick=()=>{const form=document.getElementById('publicBookingForm');if(!form.reportValidity())return;const v=Object.fromEntries(new FormData(form).entries());Object.assign(state.values,v);const code=ATT.appointmentCode(data);const appointment={id:ATT.uid('CIT'),bookingCode:code,date:state.date,time:state.time,end:state.values.end,person:v.person,document:v.document,phone:v.phone,email:v.email,service:state.service.name,host:v.host,modality:v.modality,status:'Confirmada',notes:v.notes||'',source:'Portal público',privacyNoticeAccepted:true,createdAt:`${ATT.nowDate()} ${ATT.nowTime()}`};data.appointments.push(appointment);ATT.upsertContact(data,v);ATT.notify(data,{title:'Confirmación de cita',message:`${appointment.service} · ${appointment.date} ${appointment.time}`,channel:'Correo',recipient:appointment.email,status:'Pendiente',relatedType:'Cita',relatedId:appointment.id});ATT.notify(data,{title:'Nueva cita asignada',message:`${appointment.person} · ${appointment.date} ${appointment.time}`,channel:'Notificación interna',recipient:appointment.host,status:'Pendiente',relatedType:'Cita',relatedId:appointment.id});ATT.audit(data,'Portal público','Crear cita','Cita',appointment.id,code);save();state.appointment=appointment;setStep(4);};}
  function confirmStep(){const a=state.appointment;const qr=encodeURIComponent(ATT.checkinUrl(a.bookingCode));content.innerHTML=`<div class="confirmation"><div><span class="public-overline" style="color:var(--brand)">Cita confirmada</span><h2>Tu reserva quedó registrada</h2><p>Conserva el código para consultar, cancelar, reprogramar o registrar tu llegada.</p><span class="confirmation-code">${ATT.esc(a.bookingCode)}</span><div class="appointment-result"><strong>${ATT.esc(a.service)}</strong><p>${ATT.fmtDate(a.date)} · ${a.time}–${a.end}<br>${ATT.esc(a.host)} · ${ATT.esc(a.modality)}</p></div><div class="booking-actions"><button class="public-btn secondary" id="downloadICS">Agregar al calendario</button><button class="public-btn" id="newBooking">Reservar otra cita</button></div></div><div><img alt="Código QR para registrar llegada" src="https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${qr}"><small style="display:block;text-align:center;color:var(--muted);margin-top:7px">Escanéalo al llegar</small></div></div>`;document.getElementById('downloadICS').onclick=()=>ATT.downloadICS(a);document.getElementById('newBooking').onclick=()=>{Object.assign(state,{step:1,service:null,date:'',time:'',values:{},appointment:null});setStep(1);};}
  function render(){if(state.step===1)serviceStep();else if(state.step===2)dateStep();else if(state.step===3)dataStep();else confirmStep();}
  document.getElementById('findAppointment').onclick=()=>{const code=document.getElementById('manageCode').value.trim().toUpperCase();const last=document.getElementById('manageDocument').value.trim();const a=data.appointments.find(x=>String(x.bookingCode||'').toUpperCase()===code&&String(x.document||'').replace(/\D/g,'').endsWith(last));if(!a){document.getElementById('manageResult').innerHTML='<div class="appointment-result" style="color:var(--danger)">No se encontró una cita con esos datos.</div>';return;}document.getElementById('manageResult').innerHTML=`<div class="appointment-result"><strong>${ATT.esc(a.service)}</strong><p>${ATT.fmtDate(a.date)} · ${a.time}<br>${ATT.esc(a.status)} · ${ATT.esc(a.host)}</p><div style="display:flex;gap:6px;margin-top:8px"><button class="public-btn secondary" id="manageICS">Calendario</button>${!['Cancelada','Finalizada'].includes(a.status)?'<button class="public-btn secondary" id="manageCancel">Cancelar</button>':''}</div></div>`;document.getElementById('manageICS').onclick=()=>ATT.downloadICS(a);const c=document.getElementById('manageCancel');if(c)c.onclick=()=>{if(confirm('¿Cancelar esta cita?')){a.status='Cancelada';ATT.notify(data,{title:'Cita cancelada',message:`${a.service} · ${a.date} ${a.time}`,channel:'Correo',recipient:a.email,status:'Pendiente',relatedId:a.id});ATT.audit(data,'Portal público','Cancelar cita','Cita',a.id,a.bookingCode);save();document.getElementById('findAppointment').click();}};};
  render();ERP.refreshIcons();
});
